[ext-yaml]
[[ext-yaml.files]]
from = "Releases/Latest"
to = "${ext-root}"
include = "YamlDotNet.*"

[ext-editor-yaml]
[[ext-editor-yaml.files]]
from = "Releases/Latest"
to = "${ext-editor-root}"
include = "YamlDotNet.*"

